<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore\Models\Operations;

use \php\petstore\Utils\SpeakeasyMetadata;
class GetAnimalsByIdRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\php\petstore\Models\Shared\Animals $animals = null;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=perPage')]
    public ?int $perPage = null;
    
	public function __construct()
	{
		$this->animals = null;
		$this->id = "";
		$this->perPage = null;
	}
}
