<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore\Models\Operations;


class GetAllLivingThings200ApplicationJSON1Meta
{
	#[\JMS\Serializer\Annotation\SerializedName('pagination')]
    #[\JMS\Serializer\Annotation\Type('php\petstore\Models\Operations\GetAllLivingThings200ApplicationJSON1MetaPagination')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?GetAllLivingThings200ApplicationJSON1MetaPagination $pagination = null;
    
	public function __construct()
	{
		$this->pagination = null;
	}
}
