<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore\Models\Operations;

use \php\petstore\Utils\SpeakeasyMetadata;
class GetAllLivingThingsRequest
{
    /**
     * include all filters
     * 
     * @var ?array<mixed> $filter
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=filter')]
    public ?array $filter = null;
    
	public function __construct()
	{
		$this->filter = null;
	}
}
