<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore\Models\Operations;


class GetAllLivingThings200ApplicationJSON1
{
    /**
     * $birds
     * 
     * @var ?array<\php\petstore\Models\Shared\Birds> $birds
     */
	#[\JMS\Serializer\Annotation\SerializedName('birds')]
    #[\JMS\Serializer\Annotation\Type('array<php\petstore\Models\Shared\Birds>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $birds = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('meta')]
    #[\JMS\Serializer\Annotation\Type('php\petstore\Models\Operations\GetAllLivingThings200ApplicationJSON1Meta')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?GetAllLivingThings200ApplicationJSON1Meta $meta = null;
    
	public function __construct()
	{
		$this->birds = null;
		$this->meta = null;
	}
}
