<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore\Models\Operations;


class Meta
{
	#[\JMS\Serializer\Annotation\SerializedName('pagination')]
    #[\JMS\Serializer\Annotation\Type('php\petstore\Models\Shared\Pagination')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\php\petstore\Models\Shared\Pagination $pagination = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('traceId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $traceId = null;
    
	public function __construct()
	{
		$this->pagination = null;
		$this->traceId = null;
	}
}
