<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore\Models\Operations;

use \php\petstore\Utils\SpeakeasyMetadata;
class UpdateAnimalsByIdRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\php\petstore\Models\Shared\Animals $animals = null;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;
    
	public function __construct()
	{
		$this->animals = null;
		$this->id = "";
	}
}
