<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore\Models\Shared;


class ComplexObjectDataBirds
{
    /**
     * $food
     * 
     * @var array<string> $food
     */
	#[\JMS\Serializer\Annotation\SerializedName('food')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $food;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	public function __construct()
	{
		$this->food = [];
		$this->id = "";
		$this->name = "";
	}
}
