<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore\Models\Shared;


class ComplexObjectData
{
    /**
     * $animal
     * 
     * @var ?array<\php\petstore\Models\Shared\Animals> $animal
     */
	#[\JMS\Serializer\Annotation\SerializedName('animal')]
    #[\JMS\Serializer\Annotation\Type('array<php\petstore\Models\Shared\Animals>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $animal = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('birds')]
    #[\JMS\Serializer\Annotation\Type('php\petstore\Models\Shared\ComplexObjectDataBirds')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ComplexObjectDataBirds $birds = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('createdDate')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public mixed $createdDate = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('updatedDate')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public mixed $updatedDate = null;
    
	public function __construct()
	{
		$this->animal = null;
		$this->birds = null;
		$this->createdDate = null;
		$this->updatedDate = null;
	}
}
