<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore\Models\Shared;


class Location
{
	#[\JMS\Serializer\Annotation\SerializedName('geography')]
    #[\JMS\Serializer\Annotation\Type('php\petstore\Models\Shared\Geography')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Geography $geography = null;
    
	public function __construct()
	{
		$this->geography = null;
	}
}
