<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore\Models\Shared;


class NestedBirdFlight
{
	#[\JMS\Serializer\Annotation\SerializedName('canFly')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $canFly = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('wings')]
    #[\JMS\Serializer\Annotation\Type('php\petstore\Models\Shared\NestedBirdFlightWings')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?NestedBirdFlightWings $wings = null;
    
	public function __construct()
	{
		$this->canFly = null;
		$this->wings = null;
	}
}
