<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore\Models\Shared;


class NestedBirdFlightWings
{
	#[\JMS\Serializer\Annotation\SerializedName('count')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $count = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('span')]
    #[\JMS\Serializer\Annotation\Type('php\petstore\Models\Shared\NestedBirdFlightWingsSpan')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?NestedBirdFlightWingsSpan $span = null;
    
	public function __construct()
	{
		$this->count = null;
		$this->span = null;
	}
}
