<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore\Models\Shared;


enum NestedBirdAgeUnit: string
{
    case Months = 'months';
    case Years = 'years';
    case Days = 'days';
}
