<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore\Models\Shared;


class NestedBirdAge
{
	#[\JMS\Serializer\Annotation\SerializedName('amount')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $amount = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('unit')]
    #[\JMS\Serializer\Annotation\Type('enum<php\petstore\Models\Shared\NestedBirdAgeUnit>')]
    public NestedBirdAgeUnit $unit;
    
	public function __construct()
	{
		$this->amount = null;
		$this->unit = \php\petstore\Models\Shared\NestedBirdAgeUnit::Months;
	}
}
