<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore\Models\Shared;


class NestedBird
{
	#[\JMS\Serializer\Annotation\SerializedName('age')]
    #[\JMS\Serializer\Annotation\Type('php\petstore\Models\Shared\NestedBirdAge')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?NestedBirdAge $age = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('flight')]
    #[\JMS\Serializer\Annotation\Type('php\petstore\Models\Shared\NestedBirdFlight')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?NestedBirdFlight $flight = null;
    
    /**
     * $food
     * 
     * @var ?array<string> $food
     */
	#[\JMS\Serializer\Annotation\SerializedName('food')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $food = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
    /**
     * $location
     * 
     * @var ?array<\php\petstore\Models\Shared\NestedBirdLocation> $location
     */
	#[\JMS\Serializer\Annotation\SerializedName('location')]
    #[\JMS\Serializer\Annotation\Type('array<php\petstore\Models\Shared\NestedBirdLocation>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $location = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
	public function __construct()
	{
		$this->age = null;
		$this->flight = null;
		$this->food = null;
		$this->id = null;
		$this->location = null;
		$this->name = null;
	}
}
