<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore\Models\Shared;

use \php\petstore\Utils\SpeakeasyMetadata;
class Security
{
	#[SpeakeasyMetadata('security:scheme=true,type=oauth2,name=Authorization')]
    public ?string $key1 = null;
    
	public function __construct()
	{
		$this->key1 = null;
	}
}
