<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace php\petstore;

class Animals 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * create an animal
     * 
     * Post animals description
     * 
     * @param \php\petstore\Models\Operations\CreateAnimalRequestBody $request
     * @param \php\petstore\Models\Operations\CreateAnimalSecurity $security
     * @return \php\petstore\Models\Operations\CreateAnimalResponse
     */
	public function createAnimal(
        ?\php\petstore\Models\Operations\CreateAnimalRequestBody $request,
        \php\petstore\Models\Operations\CreateAnimalSecurity $security,
    ): \php\petstore\Models\Operations\CreateAnimalResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/animals');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "request", "json");
        if ($body !== null) {
            $options = array_merge_recursive($options, $body);
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \php\petstore\Models\Operations\CreateAnimalResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->animals = $serializer->deserialize((string)$httpResponse->getBody(), 'php\petstore\Models\Shared\Animals', 'json');
            }
        }
        else if ($httpResponse->getStatusCode() === 500) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->error = $serializer->deserialize((string)$httpResponse->getBody(), 'php\petstore\Models\Shared\Error', 'json');
            }
        }

        return $response;
    }
	
    /**
     * create a living thing
     * 
     * Create a living thing
     * 
     * @param \php\petstore\Models\Shared\ComplexObject $request
     * @return \php\petstore\Models\Operations\CreateLivingThingsResponse
     */
	public function createLivingThings(
        ?\php\petstore\Models\Shared\ComplexObject $request,
    ): \php\petstore\Models\Operations\CreateLivingThingsResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/living-things');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "request", "json");
        if ($body !== null) {
            $options = array_merge_recursive($options, $body);
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $httpResponse = $this->sdkConfiguration->defaultClient->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \php\petstore\Models\Operations\CreateLivingThingsResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->complexObject = $serializer->deserialize((string)$httpResponse->getBody(), 'php\petstore\Models\Shared\ComplexObject', 'json');
            }
        }
        else if ($httpResponse->getStatusCode() === 500) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->error = $serializer->deserialize((string)$httpResponse->getBody(), 'php\petstore\Models\Shared\Error', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Delete Animal Object
     * 
     * Delete the animal
     * 
     * @param \php\petstore\Models\Operations\DeleteAnimalsByIdRequest $request
     * @return \php\petstore\Models\Operations\DeleteAnimalsByIdResponse
     */
	public function deleteAnimalsById(
        ?\php\petstore\Models\Operations\DeleteAnimalsByIdRequest $request,
    ): \php\petstore\Models\Operations\DeleteAnimalsByIdResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/animals/{id}', \php\petstore\Models\Operations\DeleteAnimalsByIdRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $httpResponse = $this->sdkConfiguration->defaultClient->request('DELETE', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \php\petstore\Models\Operations\DeleteAnimalsByIdResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
        }
        else if ($httpResponse->getStatusCode() === 500) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->error = $serializer->deserialize((string)$httpResponse->getBody(), 'php\petstore\Models\Shared\Error', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Your GET endpoint
     * 
     * Get Animals Description
     * 
     * @param \php\petstore\Models\Operations\GetAllAnimalsRequest $request
     * @return \php\petstore\Models\Operations\GetAllAnimalsResponse
     */
	public function getAllAnimals(
        ?\php\petstore\Models\Operations\GetAllAnimalsRequest $request,
    ): \php\petstore\Models\Operations\GetAllAnimalsResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/animals');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\php\petstore\Models\Operations\GetAllAnimalsRequest::class, $request, null));
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $httpResponse = $this->sdkConfiguration->defaultClient->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \php\petstore\Models\Operations\GetAllAnimalsResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->animals = $serializer->deserialize((string)$httpResponse->getBody(), 'array<php\petstore\Models\Shared\Animals>', 'json');
            }
        }
        else if ($httpResponse->getStatusCode() === 500) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->error = $serializer->deserialize((string)$httpResponse->getBody(), 'php\petstore\Models\Shared\Error', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Get All living things
     * 
     * get All living things data
     * 
     * @param \php\petstore\Models\Operations\GetAllLivingThingsRequest $request
     * @return \php\petstore\Models\Operations\GetAllLivingThingsResponse
     */
	public function getAllLivingThings(
        ?\php\petstore\Models\Operations\GetAllLivingThingsRequest $request,
    ): \php\petstore\Models\Operations\GetAllLivingThingsResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/living-things');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\php\petstore\Models\Operations\GetAllLivingThingsRequest::class, $request, null));
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $httpResponse = $this->sdkConfiguration->defaultClient->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \php\petstore\Models\Operations\GetAllLivingThingsResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->getAllLivingThings200ApplicationJSONObject = $serializer->deserialize((string)$httpResponse->getBody(), 'mixed', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Get Animal
     * 
     * Get an animal
     * 
     * @param \php\petstore\Models\Operations\GetAnimalsByIdRequest $request
     * @param \php\petstore\Models\Operations\GetAnimalsByIdSecurity $security
     * @return \php\petstore\Models\Operations\GetAnimalsByIdResponse
     */
	public function getAnimalsById(
        ?\php\petstore\Models\Operations\GetAnimalsByIdRequest $request,
        \php\petstore\Models\Operations\GetAnimalsByIdSecurity $security,
    ): \php\petstore\Models\Operations\GetAnimalsByIdResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/animals/{id}', \php\petstore\Models\Operations\GetAnimalsByIdRequest::class, $request);
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "animals", "json");
        if ($body !== null) {
            $options = array_merge_recursive($options, $body);
        }
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\php\petstore\Models\Operations\GetAnimalsByIdRequest::class, $request, null));
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \php\petstore\Models\Operations\GetAnimalsByIdResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->animals = $serializer->deserialize((string)$httpResponse->getBody(), 'php\petstore\Models\Shared\Animals', 'json');
            }
        }
        else if ($httpResponse->getStatusCode() === 500) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->error = $serializer->deserialize((string)$httpResponse->getBody(), 'php\petstore\Models\Shared\Error', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Update Animal
     * 
     * Update the animal object
     * 
     * @param \php\petstore\Models\Operations\UpdateAnimalsByIdRequest $request
     * @param \php\petstore\Models\Operations\UpdateAnimalsByIdSecurity $security
     * @return \php\petstore\Models\Operations\UpdateAnimalsByIdResponse
     */
	public function updateAnimalsById(
        ?\php\petstore\Models\Operations\UpdateAnimalsByIdRequest $request,
        \php\petstore\Models\Operations\UpdateAnimalsByIdSecurity $security,
    ): \php\petstore\Models\Operations\UpdateAnimalsByIdResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/animals/{id}', \php\petstore\Models\Operations\UpdateAnimalsByIdRequest::class, $request);
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "animals", "json");
        if ($body !== null) {
            $options = array_merge_recursive($options, $body);
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('PATCH', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \php\petstore\Models\Operations\UpdateAnimalsByIdResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->animals = $serializer->deserialize((string)$httpResponse->getBody(), 'php\petstore\Models\Shared\Animals', 'json');
            }
        }
        else if ($httpResponse->getStatusCode() === 500) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->error = $serializer->deserialize((string)$httpResponse->getBody(), 'php\petstore\Models\Shared\Error', 'json');
            }
        }

        return $response;
    }
}